site_name: onequant
site_url: https://xunzhimeng.github.io/onequant
repo_url: https://github.com/xunzhimeng/onequant
repo_name: xunzhimeng/onequant
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules:
    - onequant.md
    - api/api_request.md
    - api/api_wrapper.md
    - api/api_trades.md
    - api/api_strategies.md
    - api/api_quotes.md
    - datawash/preprocess_returns.md
    - portfolio/portfolio.md
    - util/datetime.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - onequant
      # options:
      #     show_root_heading: true
      #     show_source: false
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: https://github.com/DarkDemiurg/cookiecutter-pypackage
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: https://github.com/DarkDemiurg/cookiecutter-pypackage
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/xunzhimeng/onequant
      name: Github
    - icon: material/email
      link: "mailto:zhiyiquant@foxmail.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
